name: sayble
description: "Sayble."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  flutter_keyboard_visibility: ^6.0.0
  font_awesome_flutter: ^9.1.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_staggered_grid_view: ^0.4.0
  image_picker: ^1.1.2
  uni_links: ^0.5.1
  fluttertoast: ^8.0.8
  qr_flutter: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/assets/fonts/
    - lib/assets/jpegs/
  fonts:
      - family: Sayble
        fonts:
         - asset: lib/assets/fonts/Sayble.ttf

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
